Haldur/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Haldur;
using System.IO;

namespace Haldur
{
   partial class File
    {
        public string FileNameShort => FileName.Split('\\').Reverse().Take(1).SingleOrDefault();
    }
}


namespace Haldur.Controllers
{
    public class FilesController : Controller
    {
        private HaldurEntities db = new HaldurEntities();

        public ActionResult FileImage(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            File c = db.Files.Find(id.Value);
            if (c == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (c.Content?.Length == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var picture = c.Content.ToArray();
            if (picture[0] == 21) picture = picture.Skip(78).ToArray();
            return File(picture,  c.FileType ?? "image/jpg");
        }

        // GET: Files
        public ActionResult Index(string sortOrder, string searchString, string sortDirection)
        {
           
            var files = db.Files.Include(f => f.Project).Include(f => f.Task).AsEnumerable();

            ViewBag.Reverse = sortDirection == null || sortDirection == "" ? "" : "desc";
            ViewBag.SortParm = String.IsNullOrEmpty(sortOrder) ? "name" : sortOrder;
            //ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "name";

            if (!String.IsNullOrEmpty(searchString))
            {
                files = files.Where(s => s.Project.ProjectName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "projectname":
                    files = files.OrderBy(s => s.Project.ProjectName);
                    break;
                case "taskname":
                    files = files.OrderBy(s => s.Task.TaskName);
                    break;
            }
            if (sortOrder == "desc") files = files.Reverse();
            return View(files.ToList());
        }




        // GET: Files/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
            
        }

        // GET: Files/Create
        public ActionResult Create()
        {
            ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "ProjectName");
            ViewBag.TaskID = new SelectList(db.Tasks, "TaskID", "TaskName");
            return View();
        }

        // POST: Files/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FileID,FileName,FileType,ProjectID,TaskID,Content")] File file)
        {
            if (ModelState.IsValid)
            {
                db.Files.Add(file);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "ProjectName", file.ProjectID);
            ViewBag.TaskID = new SelectList(db.Tasks, "TaskID", "TaskName", file.TaskID);
            return View(file);
        }

        // GET: Files/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "ProjectName", file.ProjectID);
            ViewBag.TaskID = new SelectList(db.Tasks, "TaskID", "TaskName", file.TaskID);
            return View(file);
        }

        // POST: Files/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FileID,FileName,FileType,ProjectID,TaskID")] File sisu, HttpPostedFileBase file = null)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sisu).State = EntityState.Modified;
                db.Entry(sisu).Property(x => x.Content).IsModified = false;
                if (file != null && file.ContentLength > 0)
                {
                    using (BinaryReader br = new BinaryReader(file.InputStream))
                    {
                        byte[] buff = br.ReadBytes(file.ContentLength);
                        sisu.Content = buff;
                        sisu.FileName = file.FileName;
                        sisu.FileType = file.ContentType;
                    }
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "ProjectName", sisu.ProjectID);
            ViewBag.TaskID = new SelectList(db.Tasks, "TaskID", "TaskName", sisu.TaskID);
            return View(sisu);
        }

        // GET: Files/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        // POST: Files/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            File file = db.Files.Find(id);
            db.Files.Remove(file);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Haldur/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Haldur;

namespace Haldur.Controllers
{
    public class RolesController : Controller
    {
        private HaldurEntities db = new HaldurEntities();

        // GET: Roles
        public ActionResult Index()
        {
            var roles = db.Roles;
            return View(roles.ToList());
        }

        // GET: Roles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // GET: Roles/Create
        public ActionResult Create()
        {
            //ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName");
            ViewBag.Role1 = new SelectList(db.Roles, "ID", "Role1");
            return View();
        }



        // POST: Roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Role1,Description")] Role role)
            
        {
            if (ModelState.IsValid)
            {
                db.Roles.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(role);
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UserID,Role1,Description")] Role role)
        {
            if (ModelState.IsValid)
            {
                db.Entry(role).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Role role = db.Roles.Find(id);
            db.Roles.Remove(role);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Haldur/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Haldur;
using H = Haldur;


namespace Haldur
{
    partial class User
    {
        static HaldurEntities db = new HaldurEntities();
        public static User GetByEmail(string email)
            => db.Users.Where(x => x.EMail == email).SingleOrDefault();

        public bool IsInRole (string roleName)
               => this.UserProjectRoles    // vaatan kasutaja küljes olevaid rolle
                .Select(x => x.Role.Role1.ToLower()) // leian iga rolli nime
                .Contains(roleName.ToLower()); // kontrollin, kas küsitav roll on nende hulgas

        public string FullName => FirstName + " " + LastName;

        
    }


}

namespace Haldur.Controllers
{
    public class UsersController : Controller
    {
        private HaldurEntities db = new HaldurEntities();

        // GET: Users
        public ActionResult Index(string sortOrder, string searchString, string sortDirection)
        {
            var kasutajad = db.Users.AsEnumerable();

            ViewBag.Reverse = sortDirection == null || sortDirection == "" ? "" : "desc";

            User u = H.User.GetByEmail(User.Identity.Name);
            ViewBag.CurrentUser = u;
            ViewBag.SortParm = String.IsNullOrEmpty(sortOrder) ? "name" : sortOrder;

            if (!String.IsNullOrEmpty(searchString))
            {
                kasutajad = kasutajad.Where(s => s.EMail.Contains(searchString));
            }

            
            switch (sortOrder)
            {
                case "lastname":
                    kasutajad = kasutajad.OrderBy(s => s.LastName);
                    break;
                case "firstname":
                    kasutajad = kasutajad.OrderBy(s => s.FirstName);
                    break;
                case "username":
                    kasutajad = kasutajad.OrderBy(s => s.UserName);
                    break;
                case "email":
                    kasutajad = kasutajad.OrderBy(s => s.EMail);
                    break;
                case "org":
                    kasutajad = kasutajad.OrderBy(s => s.Company);
                    break;
            }
            if (sortOrder == "desc") kasutajad = kasutajad.Reverse();
            return View(kasutajad.ToList());
         }


        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            User u = new User { EMail = User.Identity.Name };
            return View(u);
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserID,UserName,FirstName,LastName,EMail,Phone,Company")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index", "Projects");
            }

            return  RedirectToAction("Index", "Projects");
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,UserName,FirstName,LastName,EMail,Phone,Company")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Haldur/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>@ViewBag.Title - HALDUR</title>
    @*@Styles.Render("~/Content/css")*@
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
    <link rel="stylesheet" href="@Url.Content("~/Content/jquery-ui/jquery-ui.min.css")" />
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HALDUR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Projektid", "Index", "Projects")</li>
                        <li>@Html.ActionLink("Tööülesanded", "Index", "Tasks")</li>
                        <li>@Html.ActionLink("Failid", "Index", "Files")</li>
                        <li>@Html.ActionLink("Kontaktid", "Index", "Users")</li>


                        Haldur.User u = Haldur.User.GetByEmail(User.Identity.Name);


                        if (u?.IsInRole("ADM") ?? false)

                        {
                            <li>@Html.ActionLink("Õiguste haldus", "Index", "UserProjectRoles")</li>
                            <li>@Html.ActionLink("Rollide lisamine", "Index", "Roles")</li>

                        }
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />

        @Scripts.Render("~/bundles/jquery")
        <script src="@Url.Content("~/Content/jquery-ui/jquery-ui.min.js")"></script>
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)


    </div>
    <footer>
        <p align="center"> @Html.ActionLink("Võta meiega ühendust", "contact", "Home")</p>
        <p align="center">&copy; @DateTime.Now.Year - HALDUR</p>
    </footer>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)*@
    <script>
        $(document).ready(function () {

            $('.datepicker').datepicker({
                dateFormat: 'dd.mm.yy'
            });

        });

    </script>
    <script>
        /* Estonian initialisation for the jQuery UI date picker plugin. */
        /* Written by Mart Sõmermaa (mrts.pydev at gmail com). */
        (function (factory) {
            if (typeof define === "function" && define.amd) {
                // AMD. Register as an anonymous module.
                define(["../widgets/datepicker"], factory);
            } else {
                // Browser globals
                factory(jQuery.datepicker);
            }
        }(function (datepicker) {
            datepicker.regional.et = {
                closeText: "Sulge",
                prevText: "Eelnev",
                nextText: "Järgnev",
                currentText: "Täna",
                monthNames: ["Jaanuar", "Veebruar", "Märts", "Aprill", "Mai", "Juuni",
                    "Juuli", "August", "September", "Oktoober", "November", "Detsember"],
                monthNamesShort: ["Jaan", "Veebr", "Märts", "Apr", "Mai", "Juuni",
                    "Juuli", "Aug", "Sept", "Okt", "Nov", "Dets"],
                dayNames: [
                    "Pühapäev",
                    "Esmaspäev",
                    "Teisipäev",
                    "Kolmapäev",
                    "Neljapäev",
                    "Reede",
                    "Laupäev"
                ],
                dayNamesShort: ["Pühap", "Esmasp", "Teisip", "Kolmap", "Neljap", "Reede", "Laup"],
                dayNamesMin: ["P", "E", "T", "K", "N", "R", "L"],
                weekHeader: "näd",
                dateFormat: "dd.mm.yy",
                firstDay: 1,
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix: ""
            };
            datepicker.setDefaults(datepicker.regional.et);
            return datepicker.regional.et;
        }));
    </script>
</body>
</html>