Haldur/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Haldur;
using System.IO;

namespace Haldur
{
   partial class File
    {
        public string FileNameShort => FileName.Split('\\').Reverse().Take(1).SingleOrDefault();
    }
}


namespace Haldur.Controllers
{
    public class FilesController : Controller
    {
        private HaldurEntities db = new HaldurEntities();

        public ActionResult FileImage(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            File c = db.Files.Find(id.Value);
            if (c == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (c.Content?.Length == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var picture = c.Content.ToArray();
            if (picture[0] == 21) picture = picture.Skip(78).ToArray();
            return File(picture,  c.FileType ?? "image/jpg");
        }

        // GET: Files
        public ActionResult Index(string sortOrder, string searchString, string sortDirection)
        {
           
            var files = db.Files.Include(f => f.Project).Include(f => f.Task).AsEnumerable();

            ViewBag.Reverse = sortDirection == null || sortDirection == "" ? "" : "desc";
            ViewBag.SortParm = String.IsNullOrEmpty(sortOrder) ? "name" : sortOrder;
            //ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "name";

            if (!String.IsNullOrEmpty(searchString))
            {
                files = files.Where(s => s.Project.ProjectName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "projectname":
                    files = files.OrderBy(s => s.Project.ProjectName);
                    break;
                case "taskname":
                    files = files.OrderBy(s => s.Task.TaskName);
                    break;
            }
            if (sortOrder == "desc") files = files.Reverse();
            return View(files.ToList());
        }




        // GET: Files/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
            
        }

        // GET: Files/Create
        public ActionResult Create()
        {
            ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "ProjectName");
            ViewBag.TaskID = new SelectList(db.Tasks, "TaskID", "TaskName");
            return View();
        }

        // POST: Files/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FileID,FileName,FileType,ProjectID,TaskID,Content")] File file)
        {
            if (ModelState.IsValid)
            {
                db.Files.Add(file);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "ProjectName", file.ProjectID);
            ViewBag.TaskID = new SelectList(db.Tasks, "TaskID", "TaskName", file.TaskID);
            return View(file);
        }

        // GET: Files/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "ProjectName", file.ProjectID);
            ViewBag.TaskID = new SelectList(db.Tasks, "TaskID", "TaskName", file.TaskID);
            return View(file);
        }

        // POST: Files/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FileID,FileName,FileType,ProjectID,TaskID")] File sisu, HttpPostedFileBase file = null)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sisu).State = EntityState.Modified;
                db.Entry(sisu).Property(x => x.Content).IsModified = false;
                if (file != null && file.ContentLength > 0)
                {
                    using (BinaryReader br = new BinaryReader(file.InputStream))
                    {
                        byte[] buff = br.ReadBytes(file.ContentLength);
                        sisu.Content = buff;
                        sisu.FileName = file.FileName;
                        sisu.FileType = file.ContentType;
                    }
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "ProjectName", sisu.ProjectID);
            ViewBag.TaskID = new SelectList(db.Tasks, "TaskID", "TaskName", sisu.TaskID);
            return View(sisu);
        }

        // GET: Files/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        // POST: Files/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            File file = db.Files.Find(id);
            db.Files.Remove(file);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Haldur/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Haldur;
using H = Haldur;


namespace Haldur.Controllers
{
    public class TasksController : Controller
    {
        private HaldurEntities db = new HaldurEntities();

    
        //GET: Tasks
        public ActionResult Index(int? id, string sortOrder, string searchString, string sortDirection)


        {
           
            var tasks = db.Tasks.Include(t => t.Worker).Include(t => t.Assigner).AsEnumerable();

            ViewBag.Reverse = sortDirection == null || sortDirection == "" ? "" : "desc";

            User u = H.User.GetByEmail(User.Identity.Name);
            if (u == null) return RedirectToAction("Login", "Account");
            ViewBag.CurrentUser = u;
            ViewBag.SortParm = String.IsNullOrEmpty(sortOrder) ? "name" : sortOrder;

            if (u.IsInRole("ADM"))
            {
                tasks = db.Tasks.Include(t => t.Worker).Include(t => t.Assigner);
            }
            else
            {
                ViewBag.UserId = u.UserID;
                tasks = tasks.Where(t => t.AssignedTo == u.UserID || t.AssignedBy == u.UserID);
            }

            //ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "name";
            ViewBag.DateSortParmStart = sortOrder == "Date" ? "date_descstart" : "Date_start";
            ViewBag.DateSortParmEnd = sortOrder == "Date" ? "date_descend" : "Date_end";
            if (!String.IsNullOrEmpty(searchString))
            {
                tasks = tasks.Where(s => s.Project.ProjectName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "taskname":
                    tasks = tasks.OrderBy(s => s.TaskName);
                    break;
                case "state":
                    tasks = tasks.OrderBy(s => s.State);
                    break;
                //case "name":
                //    tasks = tasks.OrderBy(s => s.State);
                //    tasks = tasks.OrderBy(s => s.TaskName);
                //    ViewBag.NameSortParm = "name_desc";
                //    break;
                case "Date_start":
                    tasks = tasks.OrderBy(p => p.StartDate);
                    break;
                case "date_descstart":
                    tasks = tasks.OrderByDescending(s => s.StartDate);
                    break;
                case "Date_end":
                    tasks = tasks.OrderBy(p => p.EndDate);
                    break;
                case "date_descend":
                    tasks = tasks.OrderByDescending(s => s.EndDate);
                    break;
                default:
                    tasks = tasks.OrderBy(p => p.StartDate);
                    break;
            }
            if (sortOrder == "desc") tasks = tasks.Reverse();
            return View(tasks.ToList());

        }
        //GET: Tasks/Details/5

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // GET: Tasks/Create
        public ActionResult Create(int? id)
        {
            User u = H.User.GetByEmail(User.Identity.Name);
            if (u == null) return RedirectToAction("Login", "Account");
            if (id.HasValue)
            {

                ViewBag.ProjectNumber = id;
                ViewBag.ProjectID = new SelectList(db.Projects.Where(x => x.UserID == u.UserID), "ProjectID", "ProjectName", id.Value);
                //ViewBag.AssignedTo = new SelectList(db.Users.Where(x => x.UserProjectRoles.Select(y => y.ProjectID).Contains(id.Value)));
            }
            else
            {
                ViewBag.ProjectNumber = null;
                ViewBag.ProjectID = new SelectList(db.Projects.Where(x => x.UserID  == u.UserID), "ProjectID", "ProjectName");

            }

            ViewBag.AssignedBy = new SelectList(db.Users, "UserID", "UserName");
            ViewBag.AssignedTo = new SelectList(db.Users, "UserID", "UserName");
            ViewBag.State = new SelectList(db.Tasks, "State", "State");
            if (User.Identity.IsAuthenticated)
            {
                Task t = new Task { AssignedBy = H.User.GetByEmail(User.Identity.Name).UserID };
                ViewBag.AssignedBy = new SelectList(db.Users, "UserID", "UserName", t.AssignedBy);
                ViewBag.Assigner = H.User.GetByEmail(User.Identity.Name).UserName;
                return View(t);
            }
            else return RedirectToAction("Login", "Account");

        }



        // POST: Tasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaskID,ProjectID,TaskSequence,TaskName,AssignedBy,AssignedTo,StartDate,EndDate,State,Comment")] Task task)
        {
            if (ModelState.IsValid)
            {
                db.Tasks.Add(task);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "ProjectName", task.ProjectID);
            ViewBag.AssignedBy = new SelectList(db.Users, "UserID", "UserName", task.AssignedBy);
            ViewBag.AssignedTo = new SelectList(db.Users, "UserID", "UserName", task.AssignedTo);
            return View(task);
        }

        // GET: Tasks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "ProjectName", task.ProjectID);
                ViewBag.AssignedBy = new SelectList(db.Users, "UserID", "UserName", task.AssignedBy);
                ViewBag.AssignedTo = new SelectList(db.Users, "UserID", "UserName", task.AssignedTo);
               return View(task);

            }
            else return RedirectToAction("Login", "Account");
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TaskID,ProjectID,TaskSequence,TaskName,AssignedBy,AssignedTo,StartDate,EndDate,State,Comment")] Task task)
        {
            if (ModelState.IsValid)
            {
                db.Entry(task).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectID = new SelectList(db.Projects, "ProjectID", "ProjectName", task.ProjectID);
            ViewBag.AssignedBy = new SelectList(db.Users, "UserID", "UserName", task.AssignedBy);
            ViewBag.AssignedTo = new SelectList(db.Users, "UserID", "UserName", task.AssignedTo);
            return View(task);
        }

        // GET: Tasks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            if (User.Identity.IsAuthenticated)
            {
                return View(task);
            }
            else return RedirectToAction("Login", "Account");
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Task task = db.Tasks.Find(id);
            db.Tasks.Remove(task);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Haldur/Views/Projects/Create.cshtml
@model Haldur.Project

@{
    ViewBag.Title = "Create";
}

<h2>Loo uus</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Projekt</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, "State", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("State", new SelectList(new string[] { "Aktiivne" }), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.HiddenFor(model => model.UserID)
            <div class="col-md-10">
                @*@Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })*@
                @*@Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })*@
                @ViewBag.Owner (@Html.DisplayFor(model => model.UserID))
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Loo uus" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tagasi", "Index")
</div>

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    <script>
        $(document).ready(function () {

            $('.datepicker').datepicker({
                dateFormat: 'dd.mm.yy'   


                //$('#startDate').val($.datepicker.formatDate('dd.mm.yy', today));
            });

        });
    </script>
}

Haldur/Views/Projects/Delete.cshtml
@model Haldur.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Kustuta</h2>

<h3>Oled kindel, et soovid kustutada?</h3>
<div>
    <h4>Projekt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Kustuta" class="btn btn-default" /> |
            @Html.ActionLink("Tagasi", "Index")
        </div>
    }
</div>

Haldur/Views/Projects/Details.cshtml
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

@model Haldur.Project

@{
    ViewBag.Title = "Details";
}

<h2>Detailid </h2>

<div>
    <h4>Projekt: @Html.DisplayFor(model => model.ProjectName)</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
                @Html.DisplayNameFor(model => model.ProjectName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProjectName)
            </dd>*@

        <dt>
            @Html.DisplayName("Alguse kuupäev")
        </dt>

        <dd>
            @if (Model.StartDate.HasValue)
            {
                @Model.StartDate.Value.ToString("MM/dd/yyyy")
            }
        </dd>

        <dt>
            @Html.DisplayName("Lõpu kuupäev")
        </dt>

        <dd>
            @if (Model.StartDate.HasValue)
            {
                @Model.StartDate.Value.ToString("MM/dd/yyyy")
            }
        </dd>

        <dt>
            @Html.DisplayName("Staatus")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayName("Kommentaarid")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayName("Algataja")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

    </dl>
    <div>
        <h4>
            <br>
            Selle projekti liikmed:
        </h4>


        @foreach (var upr in Model.UserProjectRoles)
        {
            <p>
                <a href="#" title="Andmed" data-toggle="popover" data-trigger="hover" data-content='@upr.User.Phone @upr.User.EMail'> @upr.User.UserName </a> <t>on rollis</t> @upr.Role.Role1;
            </p>
        }

    </div>


    <div>
        <h4>
            <br>
            Selle projekti tööülesanded:
        </h4>


        @foreach (var upr in Model.Tasks)
        {
            <p>
                <a href="#" title="Andmed" data-toggle="popover" data-trigger="hover" data-content='@upr.TaskID'> @upr.TaskName </a> <t>on projektile lisatud</t>;
            </p>
        }

    </div>


    <div>
        <h4>
            <br>
            Selle projekti failid:
        </h4>


        @foreach (var upr in Model.Files)
        {
        <p>
            <a href='@Url.Action( "FileImage", "Files", new { id = upr.FileID} )' title="Fail" data-toggle="popover" data-trigger="hover" data-content='@upr.FileType'> @upr.FileName </a> <t>on projektile lisatud</t>;

        </p>

        }

    </div>

</div>
    <p>
        <br>
        @Html.ActionLink("Muuda", "Edit", new { id = Model.ProjectID }) |
        @Html.ActionLink("Tagasi", "Index")
    </p>

    <script>
        $(document).ready(function () {
            $('[data-toggle="popover"]').popover();
        });
    </script>

Haldur/Views/Projects/Edit.cshtml
@model Haldur.Project

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProjectID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, "State", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("State", new SelectList(new string[] { "Aktiivne", "Lõpetatud" }), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control", disabled = "disabled" })
                @*@Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })*@
                @Html.HiddenFor(model => model.UserID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tagasi", "Index")
</div>

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    <script>
        $(document).ready(function () {

            $('.datepicker').datepicker({
                dateFormat: 'dd.mm.yy'
            });

        });
    </script>
}

Haldur/Views/Projects/Index.cshtml
@model IEnumerable<Haldur.Project>

@{
    ViewBag.Title = "Projektid";
}

<div style="float:left"><h2>Projektid</h2></div>
<div style="float:right"><a href="/Projects/Create/" button class="w3-button w3-xlarge w3-red">+</a></div>
<br>
<br>
<br>
<br>
<br>
<br>

@using (Html.BeginForm())
{
    <div>
        <p>
            Otsi projekti nime järgi: @Html.TextBox("SearchString")
            <input type="submit" class="w3-button w3-tiny w3-square w3-red " value="Otsi" />
        </p>
    </div>
}
<br>

@{
    var sortDirectionProjectName = ViewBag.SortParm != "projectname" ? "" : ViewBag.Reverse != "desc" ? "desc" : "";
    var sortDirectionState = ViewBag.SortParm != "state" ? "" : ViewBag.Reverse != "desc" ? "desc" : "";
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Projekti nimi", "Index", new { sortOrder = "projectname", sortDirection = (ViewBag.SortParm != "projectname" ? "" : ViewBag.Reverse != "desc" ? "desc" : "") })
        </th>
        <th>
            @Html.ActionLink("Projekti algus", "Index", new { sortOrder = ViewBag.DateSortParmStart })
        </th>
        <th>
            @Html.ActionLink("Projekti lõpp", "Index", new { sortOrder = ViewBag.DateSortParmEnd })
        </th>
        <th>
            @Html.ActionLink("Staatus", "Index", new { sortOrder = "state", sortDirection = (ViewBag.SortParm != "state" ? "" : ViewBag.Reverse != "desc" ? "desc" : "") })
        </th>
        <th>
            @Html.DisplayName("Kommentaar")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.ProjectName, "Details", new { id = item.ProjectID })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td style="float:right">
                @Html.ActionLink("Lisa ülesanne", "Create", "Tasks", new { id = item.ProjectID }, null) |
                @Html.ActionLink("Lisa tiimiliige", "Create", "UserProjectRoles", new { id = item.ProjectID }, null) |
                @Html.ActionLink("Muuda", "Edit", new { id = item.ProjectID }) |
                @Html.ActionLink("Kustuta", "Delete", new { id = item.ProjectID })
            </td>
        </tr>
    }

</table>